export const assets = {
  dialogBox: '/dialogBox.svg',
  dialogBoxDark: '/dialogBoxDark.svg',
  dialogBoxProject: '/dialogBoxProject.svg',
  dialogBoxProjectDark: '/dialogBoxProjectDark.svg',
  heroPointer: '/heroPointer.svg',
  waveBorder: '/waveBorder.svg',
  waveBottom: '/waveBottom.svg',
  waveBorderDark: '/waveBorderDark.svg',
  waveBottomDark: '/waveBottomDark.svg',
  projectsBubble: '/projectBubble.svg',
  projectScreenshot: '/projectScreenshot.png',
  projectScreenshot2: '/projectScreenshot2.png',
  isabelle: '/isabelle.png',
  weaponCircle: '/weaponCircle.svg',
  avatarFace: '/Face.svg',
  avatarFaceShocked: '/faceShocked.png',
  clouds: '/clouds.png',
  cloudsdark: '/cloudsdark.png',
  github: '/github.svg',
  linkedin: '/linkedin.png',
  spotify: '/spotify.webp',
  wifi: '/Wifi.svg',
  location: '/Location.svg',
  mail: '/mail.png',
  instagram: 'instagram.png',
  design: './palette.png',
  me1: './me1.png',
  me2: './me2.png',
  me3: './me3.png',
  dev: './dev.svg',
  tool: './tool.svg',
  star: './star.svg',
  charli: {
    n1: './sounds/note1.MP3',
    n2: './sounds/note2.MP3',
    n3: './sounds/note3.MP3',
    n4: './sounds/note4.MP3',
    n5: './sounds/note5.MP3',
    n6: './sounds/note6.MP3',
    n7: './sounds/note7.MP3',
  },
  tech: {
    react: '/tech/react.png',
    angular: '/tech/angular.png',
    next: '/tech/next.png',
    java: '/tech/java.png',
    typescript: '/tech/typescript.png',
    python: '/tech/python.png',
    css: '/tech/css.png',
    javascript: '/tech/javascript.png',
  },
} as const

export const navItems = [
  { id: 'home', label: 'Home' },
  { id: 'about', label: 'About' },
  { id: 'projects', label: 'Projects' },
  { id: 'contact', label: 'Contact' },
] as const

export type SectionId = (typeof navItems)[number]['id']
